apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://{{ include "obs.fullname" . }}-prometheus:{{ .Values.prometheus.service.port }}
    isDefault: true
    editable: true
