apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dap.frontendName" . }}
  labels:
    {{- include "dap.baseLabels" . | nindent 4 }}
    app.kubernetes.io/name: distributed-audio-pipeline
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: distributed-audio-pipeline
      app.kubernetes.io/component: frontend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "dap.baseLabels" . | nindent 8 }}
        app.kubernetes.io/name: distributed-audio-pipeline
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.port }}
