apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dap.minioName" . }}
  labels:
    {{- include "dap.baseLabels" . | nindent 4 }}
    app.kubernetes.io/name: distributed-audio-pipeline
    app.kubernetes.io/component: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: distributed-audio-pipeline
      app.kubernetes.io/component: storage
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "dap.baseLabels" . | nindent 8 }}
        app.kubernetes.io/name: distributed-audio-pipeline
        app.kubernetes.io/component: storage
    spec:
      containers:
        - name: minio
          image: "{{ .Values.minio.image.repository }}:{{ .Values.minio.image.tag }}"
          imagePullPolicy: IfNotPresent
          args:
            - server
            - /data
            - --console-address
            - :9001
          ports:
            - name: api
              containerPort: {{ .Values.minio.service.apiPort }}
            - name: console
              containerPort: {{ .Values.minio.service.consolePort }}
          env:
            - name: MINIO_ROOT_USER
              value: {{ .Values.minio.rootUser | quote }}
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "dap.fullname" . }}-secrets
                  key: minio-root-password
          volumeMounts:
            - name: data
              mountPath: /data
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: api
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: api
            initialDelaySeconds: 30
            periodSeconds: 15
      volumes:
        - name: data
          emptyDir: {}
