apiVersion: v1
kind: Service
metadata:
  name: {{ include "dap.postgresqlName" . }}
  labels:
    {{- include "dap.baseLabels" . | nindent 4 }}
    app.kubernetes.io/name: distributed-audio-pipeline
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: distributed-audio-pipeline
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
