apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dap.fullname" . }}-secrets
  labels:
    {{- include "dap.baseLabels" . | nindent 4 }}
type: Opaque
stringData:
  postgresql-password: {{ .Values.postgresql.auth.password | quote }}
  rabbitmq-password: {{ .Values.rabbitmq.auth.password | quote }}
  minio-root-password: {{ .Values.minio.rootPassword | quote }}
  auth-secret-key: {{ .Values.auth.secretKey | quote }}
