apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dap.workerName" . }}
  labels:
    {{- include "dap.baseLabels" . | nindent 4 }}
    app.kubernetes.io/name: distributed-audio-pipeline
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: distributed-audio-pipeline
      app.kubernetes.io/component: worker
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "dap.baseLabels" . | nindent 8 }}
        app.kubernetes.io/name: distributed-audio-pipeline
        app.kubernetes.io/component: worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: {{ .Values.worker.metrics.port }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.auth.username | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "dap.fullname" . }}-secrets
                  key: postgresql-password
            - name: DATABASE_URL
              value: {{ printf "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@%s:5432/%s" (include "dap.postgresqlName" .) .Values.postgresql.auth.database | quote }}
            - name: RABBITMQ_HOST
              value: {{ include "dap.rabbitmqName" . | quote }}
            - name: RABBITMQ_USER
              value: {{ .Values.rabbitmq.auth.username | quote }}
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "dap.fullname" . }}-secrets
                  key: rabbitmq-password
            - name: RABBITMQ_QUEUE
              value: audio.jobs
            - name: MINIO_ENDPOINT
              value: {{ printf "%s:%d" (include "dap.minioName" .) (.Values.minio.service.apiPort | int) | quote }}
            - name: MINIO_ACCESS_KEY
              value: {{ .Values.minio.rootUser | quote }}
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "dap.fullname" . }}-secrets
                  key: minio-root-password
            - name: MINIO_BUCKET
              value: {{ .Values.minio.bucket | quote }}
            - name: WORKER_METRICS_PORT
              value: {{ .Values.worker.metrics.port | quote }}
            - name: PYTHONUNBUFFERED
              value: "1"
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 30
            periodSeconds: 15
