apiVersion: v1
kind: Service
metadata:
  name: {{ include "dap.workerMetricsName" . }}
  labels:
    {{- include "dap.baseLabels" . | nindent 4 }}
    app.kubernetes.io/name: distributed-audio-pipeline
    app.kubernetes.io/component: worker
spec:
  type: {{ .Values.worker.metrics.service.type }}
  selector:
    app.kubernetes.io/name: distributed-audio-pipeline
    app.kubernetes.io/component: worker
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: metrics
      port: {{ .Values.worker.metrics.port }}
      targetPort: metrics
      {{- if eq .Values.worker.metrics.service.type "NodePort" }}
      nodePort: {{ .Values.worker.metrics.service.nodePort }}
      {{- end }}
