{{- if .Values.storage.prometheus.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "obs.fullname" . }}-prometheus-data
  labels:
    {{- include "obs.baseLabels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  accessModes:
    {{- toYaml .Values.storage.prometheus.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.storage.prometheus.size }}
  {{- if .Values.storage.prometheus.storageClassName }}
  storageClassName: {{ .Values.storage.prometheus.storageClassName | quote }}
  {{- end }}
{{- end }}
---
{{- if .Values.storage.grafana.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "obs.fullname" . }}-grafana-data
  labels:
    {{- include "obs.baseLabels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  accessModes:
    {{- toYaml .Values.storage.grafana.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.storage.grafana.size }}
  {{- if .Values.storage.grafana.storageClassName }}
  storageClassName: {{ .Values.storage.grafana.storageClassName | quote }}
  {{- end }}
{{- end }}
