apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "obs.fullname" . }}-prometheus
  labels:
    {{- include "obs.baseLabels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: prometheus
  template:
    metadata:
      labels:
        {{- include "obs.baseLabels" . | nindent 8 }}
        app.kubernetes.io/component: prometheus
    spec:
      containers:
        - name: prometheus
          image: "{{ .Values.prometheus.image.repository }}:{{ .Values.prometheus.image.tag }}"
          imagePullPolicy: {{ .Values.prometheus.image.pullPolicy }}
          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.path=/prometheus
            - --storage.tsdb.retention.time=15d
          ports:
            - name: http
              containerPort: {{ .Values.prometheus.service.port }}
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
            - name: config
              mountPath: /etc/prometheus/alerts.yml
              subPath: alerts.yml
            - name: data
              mountPath: /prometheus
          readinessProbe:
            httpGet:
              path: /-/ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
      volumes:
        - name: config
          configMap:
            name: {{ include "obs.fullname" . }}-prometheus-config
        - name: data
          {{- if .Values.storage.prometheus.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "obs.fullname" . }}-prometheus-data
          {{- else }}
          emptyDir: {}
          {{- end }}
